### ISSUE TITLE
Fix minor errors in funding sentence

### ISSUE THREAD

**Issue by miagaudet** [episphere/bcrpDataPlatform#38]
"The BCRPP is funded by the US National Cancer Institure (NCI) and coordinated by the Division of Cancer Epidemiology and Genetics (DCEG) of NCI and the Harvard T.H. Chan School of Public Health in collaboration with the NCI Cohort Consortium" should end with a period and correct spelling of Institute.

**Comment by bkop-ds** [comment]
Minor issues fixed.
