### ISSUE TITLE
Improve submitted concept form formatting

### ISSUE THREAD

**Issue by tahearn** [episphere/bcrpDataPlatform#65]
The submitted concept forms are a bit difficult to read. I suggest the following edits to improve readability:

1. Change the heading of the form to "Breast Cancer Risk Prediction Project Analysis Proposal"
2. Increase spacing between the fields
3. Make font size of section heading 12
4. Make font size of submitters answers 11 and don't bold the font 

Please apply other edits that you think will improve the look/readability

**Comment by bkop-ds** [comment]
1. Complete
2. Complete
3. Complete
4. Complete

Some other changes were made such as font color, spacing, in line text. It appears much better than before. Some other minor changes could also be made after your review.
