### ISSUE TITLE
Edits to labels in the DACC Menu

### ISSUE THREAD

**Issue by tahearn** [episphere/bcrpDataPlatform#68]
In the DACC Menu change the labels "To Be Completed" to "Review" and "Review" to "Re-Review"

Edit "Select Document" to read "Select Concept"

 In the current "To Be Completed" menu, change the label "Submit Comment:" to "Add Comment:", and change the label of the button "Submit & Complete" to "Submit to DACC"

**Comment by mgarciaclosas** [comment]
The DACC menu also needs to have a DACC completed tab, similar to the one for the DACC chair, but showing only the comments from the DACC chair, i.e. no all the individual DACC members.
