### ISSUE TITLE
Update data request form cohort selection section

### ISSUE THREAD

**Issue by tahearn** [episphere/bcrpDataPlatform#76]
Please replace the field asking people to write in the names of the cohorts from which they are requesting data with check boxes of the cohorts. Please use the cohorts that are listed on the study description page: https://episphere.github.io/bcrpDataPlatform/#about/description

**Comment by bkop-ds** [comment]
24 total: BWHS, BCFR, CTS, CLUE-II, CSDLH, CPS-3, CPS-II, CARET, EPIC, GSSFHS, Janus, MMHS, MCCS, MAC, MEC, NYUWHS, NHS, NHSII, SIS, SNMC, VITAL, WHI, WHS, WLH

**Comment by tahearn** [comment]
Hi Ben,
A couple of studies are missing from that list. I'll update the study description page. Here is the full list:

CSDLH, BCFR, BWHS, CARET, CLUE-II, Connect, CPS-2, CPS-3, CTS, EPIC, GS, JANUS, MAC, MCCS, MEC, MMHS, NHS, NHS-2, NYUWHS, PLCO, SISTER, SNM, VITAL, WHI, WHS, WISDOM, WLH

**Comment by bkop-ds** [comment]
Complete on form
