### ISSUE TITLE
Edit selection of cohorts on data access form

### ISSUE THREAD

**Issue by tahearn** [episphere/bcrpDataPlatform#82]
I suggest adding a "select all cohorts" check button", and on the submitted concept form if that button is selected instead of listing all the names of the cohorts we can just list "All cohorts".

If this is added the text can be edited to read "Select cohorts from which data is being requested. Proposals only requesting data from a single cohort will not be approved. If you are interested in only analyzing data from a particular cohort, please contact that cohort directly."

**Comment by bkop-ds** [comment]
remove check on mmd

**Comment by bkop-ds** [comment]
link to https://episphere.github.io/bcrpDataPlatform/#about/description
