### ISSUE TITLE
Updating User Submission and Final Decision Files View

### ISSUE THREAD

**Issue by nwray22** [episphere/bcrpDataPlatform#85]
- Enlarge the size of the Preview button and delete 'Preview' text
     -  Show tooltip on hover
 - Allow User to filter and sort on Usser Submission page
 - Moving 'User Submission' button to the navbar under Data Access
 - Display message when no files are visible

**Comment by bkop-ds** [comment]
Show columns can be sorted by having up down triangles. Currently it is hard to tell that columns are sortable.
